### ISSUE TITLE
Restore fails for concatenated strings in WP_DEBUG_LOG

### ISSUE THREAD

**Issue by noplanman** [afragen/wp-debugging#10]
As far as I can tell, the problem seems to be this line:
https://github.com/afragen/wp-debugging/blob/e18a678c96ba5337bd932d038237c2abc72694d6/src/Bootstrap.php#L200

My `wp-config.php` before:
```php
define( 'WP_DEBUG_LOG', __DIR__ . '/../logs/wp-debug.log' );
```

After restore (note the missing end quote of the file path):
```php
define( 'WP_DEBUG_LOG', __DIR__ . '/../logs/wp-debug.log );
```

**Comment by afragen** [comment]
You're right, but I don't really have a solution to adding a file path to `WP_DEBUG_LOG`. I know it works but I'm trying to sanitize my inputs.

May I suggest using `ini_set( 'error_log', __DIR__ . '/../logs/wp-debug.log' );` instead.

**Comment by afragen** [comment]
I'll see what I can do also.

**Comment by afragen** [comment]
At this time I don't honestly know why I even added that line. Just comment it out. It will likely be commented out in the next release.

**Comment by noplanman** [comment]
Was it maybe to prevent something like the quotes being saved in the string itself in some cases?

You can close off here after some more testing and when it's in the next release, thanks 🙏

**Comment by afragen** [comment]
Release v2.9.1
