### ISSUE TITLE
PHP notice replaces all post elements when WP Debugging is activated

### ISSUE THREAD

**Issue by apaleyes** [afragen/wp-debugging#11]
Hey! Thanks for the plugin, really helped us while we were debugging stuff.

But while using it we also encountered this weird behavior. We are using Gutenberg blocks, and in particular "Post Masonry". This block displays N posts/pages in columns, and offers pagination via button click or via scroll. Now apparently for some reason we are getting some PHP Notice in this block, the text of which doesn't really matter. What matters is, after we trigger pagination:
- with WP Debugging activated, all new posts that appear have their title and excerpt replaced by this PHP Notice. See attached 
image.
- with WP Debugging deactivated, everything works fine

Again, it's not the notice itself that is a problem, it is the fact that it shows up everywhere. Fwiw, we have `WP_DEBUG_DISPLAY` set to false.

![bug](https://user-images.githubusercontent.com/2852301/99467453-65556480-2936-11eb-874c-9681480d2cee.PNG)

**Comment by afragen** [comment]
Does something else have WP_DEBUG_DISPLAY set to true? If you install the Query Monitor plugin you can see these setting under Environment. 

You should also report the notice to the plugin developers.

**Comment by apaleyes** [comment]
Thanks for the reply. Just checked wp-config.php, and there is no `WP_DEBUG_DISPLAY` mentioned there. To be sure, when the WP Debugging is activated, it appears there, set to false, as expected. We don't use Query Monitor at the moment.

**Comment by afragen** [comment]
Some other plugin could be setting that constant outside of wp-config.

**Comment by apaleyes** [comment]
Alright, since there could be different plugins at play here, it's not worth keeping this open. If we manage to connect the issue direcly to WP debugging explicitly, I'll reopen
