### ISSUE TITLE
When Activated causes: Updating failed. The response is not a valid JSON response.

### ISSUE THREAD

**Issue by dbareis** [afragen/wp-debugging#14]
This plugin causes "**Updating failed. The response is not a valid JSON response.**" when updating pages.  This is on **WP 6.1.1** and Windows 11 in Chrome Browser.

PLUGIN Version: **2.11.15** for which I get this warning: "_Warning: This plugin has not been tested with your current version of WordPress._"

**Comment by afragen** [comment]
Can you provide a stacktrace?

**Comment by dbareis** [comment]
Hi,

Happy to, if you can point me to some instructions...

---
Thanks
Dennis

**Comment by afragen** [comment]
If you set `define( 'WP_DEBUG', true );` in your wp-config.php file you will see it on your screen when the error occurs.

**Comment by afragen** [comment]
Should I ask why you think this plugin is the cause?

**Comment by dbareis** [comment]
If I disable it the problem goes away and visa versa

**Comment by afragen** [comment]
The WP Debugging plugin is designed to surface errors so they can be fixed. 

Nothing in your report indicates an issue with this plugin.

**Comment by dbareis** [comment]
Hi,

Not only is the message displayed but WP doesn't think that the data has been saved so it is not just cosmetic.  For example I get a browser "leave" prompt and no "View Page" popup when it fails.

**Comment by afragen** [comment]
Can you provide instructions on how I can replicate this?

**Comment by dbareis** [comment]
For me, if it was active, it would prevent saying of any page.  I did have the debug bar on at same time and whatever 2nd plugin it recommends.

**Comment by afragen** [comment]
Is there anything in your logs, debug.log or console.log when this happens?

I ask as this plugin doesn't produced JSON for consumption. It does have a JSON file with data but that file hasn't changed in a long, long time and is valid JSON.

**Comment by afragen** [comment]
I am unable to replicate this on several sites.

**Comment by dbareis** [comment]
I have tried it again without the other two plugins and it seems to be OK now, I'll leave it enabled and see how it goes.
