### ISSUE TITLE
Do get error on some   domains on multisite

### ISSUE THREAD

**Issue by Datastream-is** [afragen/wp-debugging#15]
Hi

I'm running a multisite,  and we did use  wp-debugging some month ago.  But after update PHP 7.xx to PHP 8.0   we did get some errors on some domains.  Not all.   After we have investigated the problem,  we can see that if we enable wp-debugging we get errors on site that didn't show any errors  (like we have change the wp-config settings) and if we disable wp-debugging the error  do not display any more.  So how do the plugin works on multisite,  do it create db table for each domain that set  display debugging to true ?  this is the error that show up (see screenshot).

![Screenshot_2023-01-11 Stjórnborð ‹ Kompaníið — WordPress(1)](https://user-images.githubusercontent.com/76517647/211798658-3250b28d-1062-467a-8e59-2b07056d6491.png)

**Comment by afragen** [comment]
WP Debugging is designed to surface errors that are present. It does this by setting WP_DEBUG to true. 

Your image points to another plugin as the issue.

**Comment by Datastream-is** [comment]
Hello Andy,

 

I know that the error  points at other plugin,  I‘m not asking about that.    This is a multisite,  and the new pHP 8.0  handle error different way than php 7.xx    

 

When I  enable  wp-debugging then I get this error on all domain on the multisite,  and when I  disable it  then  the error do not show up on some of the domain‘s    in the config file this is the settings:

 

//define( 'WP_DEBUG_LOG', false );

//define( 'WP_DEBUG', false );

//define( 'WP_DEBUG_DISPLAY', false );

 

therefor it should not dilsplay any errors.  

 

Með kveðju,

 

Sigurður

GSM 867 6800

***@***.***

Datastream 

Kerfisstreymi

 

Sími: 571 6898
Síðumúla 29

 

Datastream.is

Tímabókunarkerfi

Kerfisstreymi

 

 

From: Andy Fragen ***@***.***>
Reply-To: afragen/wp-debugging ***@***.***>
Date: miðvikudagur, 11. janúar 2023 kl. 15:21
To: afragen/wp-debugging ***@***.***>
Cc: Datastream-is ***@***.***>, Author ***@***.***>
Subject: Re: [afragen/wp-debugging] Do get error on some domains on multisite (Issue #15)

 

WP Debugging is designed to surface errors that are present. It does this by setting WP_DEBUG to true.

Your image points to another plugin as the issue.

**Comment by afragen** [comment]
What are the setting in WP Debugging?

**Comment by Datastream-is** [comment]
Hello Andy,

 

We have found out what the problem was,  was not your plugin,  but thanks a lot for fast respond.

 

Með kveðju,

 

Sigurður

GSM 867 6800

***@***.***

Datastream 

Kerfisstreymi

 

Sími: 571 6898
Síðumúla 29

 

Datastream.is

Tímabókunarkerfi

Kerfisstreymi

 

 

From: Andy Fragen ***@***.***>
Reply-To: afragen/wp-debugging ***@***.***>
Date: fimmtudagur, 12. janúar 2023 kl. 12:40
To: afragen/wp-debugging ***@***.***>
Cc: Datastream-is ***@***.***>, Author ***@***.***>
Subject: Re: [afragen/wp-debugging] Do get error on some domains on multisite (Issue #15)

 

What are the setting in WP Debugging?
