### ISSUE TITLE
notice on all backend pages after activate plugin on cloudways

### ISSUE THREAD

**Issue by Tobias-Conrad** [afragen/wp-debugging#18]
Notice: Function add_submenu_page was called incorrectly. The seventh parameter passed to add_submenu_page() should be numeric representing menu position. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 5.3.0.) in /home/1301098.cloudwaysapps.com/ptvxekmtgy/public_html/wp-includes/functions.php on line 6085

Fatal error: Cannot declare class Debug_Bar, because the name is already in use in /home/1301098.cloudwaysapps.com/ptvxekmtgy/public_html/wp-content/plugins/debug-bar/debug-bar.php on line 20

sorry during creating the screencast it was not reproducing. I hope you can find the issue directly in the file and when just activate the plugin on a tastewp.com/new site

**Comment by afragen** [comment]
This plugin does not declare class Debug_Bar
