### ISSUE TITLE
Fatal Error if the wp-config.php is not writable

### ISSUE THREAD

**Issue by bueltge** [afragen/wp-debugging#3]
Hi Andy.

If the `wp-config.php` is not writable, the plugin haven't a exception and run in a Fatal error, like

>Fatal error: Uncaught Exception: wp-config.php is not writable. in /www/htdocs/wp-content/plugins/wp-debugging/vendor/wp-cli/wp-config-transformer/src/WPConfigTransformer.php:45

I think a exception and a note is more readable, more informal for users there need help with this plugin to get debugging.
Best.

**Comment by afragen** [comment]
The Exception is clearly documented in the README and it’s display is from the WP-CLI module used in this plugin. I can try to put a few more checks in to ensure the file is writable.

Thanks for the feedback.

**Comment by bueltge** [comment]
Right, I read them. However normally users install on back-end and get only a fatal error, no helpful message and the plugin is deactivated again.

**Comment by afragen** [comment]
In this case the message and the issue is in the Exception message.

**Comment by bueltge** [comment]
Yes, feel free to close the issue - however is not in my context of UI/UX and accessibility.

**Comment by afragen** [comment]
I appreciate the feedback. I simply don’t have any idea about how to intercept this Exception or modify it.

I do understand that these issues exist. I’m not sure I have any understanding of how to fix or adjust for them. Perhaps it’s worthwhile bringing up in https://github.com/wp-cli/wp-config-transformer ?
