### ISSUE TITLE
Account for up-a-level config location

### ISSUE THREAD

**Issue by Rarst** [afragen/wp-debugging#4]
The plugin currently assumes `ABSPATH` for config location. WP core supports a second case with config located a level up from there, see [`wp-load.php`](https://github.com/WordPress/WordPress/blob/ee8c3deaa5a1daff4768d554366c9cbc64a89f3a/wp-load.php#L26-L42)

**Comment by afragen** [comment]
Thanks @Rarst I will make this adjustment.

**Comment by afragen** [comment]
@Rarst does the above solve this issue?

I even added a filter hook in case the `wp-config.php` isn't one level up.

**Comment by Rarst** [comment]
Looks good. :+1:
