### ISSUE TITLE
Consider restoring state rather than removing constants on deactivation

### ISSUE THREAD

**Issue by Rarst** [afragen/wp-debugging#5]
Currently the plugin removes all of debug constants on deactivation. This seems undesirable if any of them had been previously intentionally configured (e.g. logging was enabled already).

The more considerate workflow might be to store preceding state of the constants and restore that state on deactivation.

**Comment by afragen** [comment]
The problem with trying to store the previous state is that there is no consistent method developers use. Trying to consistently find `define(‘WP_DEBUG’,true)` or `define(“WP_DEBUG”, TRUE)` or some other combination of spacing is likely to be too difficult.

Simply saving a copy of the original `wp-config.php` and reverting it may end up with more problems if something else has changed in the interim.

This action is clearly documented in the README. I can add the warning to the top of the plugin’s Settings page if you think that would be helpful.

Do you have any ideas about how to fix something like this?

**Comment by afragen** [comment]
And thanks for the feedback.

**Comment by Rarst** [comment]
From quick look WP config transformer [implements reading](https://github.com/wp-cli/wp-config-transformer/blob/9176b68b97c46853c053cc992644bf6d50a68099/src/WPConfigTransformer.php#L79-L90) (though it doesn't seem to be covered in readme).

**Comment by afragen** [comment]
Thanks. I'll take a look and see if I can figure out a way to implement this.
