### ISSUE TITLE
Add hook or text fields for custom defines

### ISSUE THREAD

**Issue by cartpauj** [afragen/wp-debugging#6]
I wonder if you’d be open to adding either a hook where we can add additional defines to be added.

Or even better some text fields in the settings page where we can enter our own defines.

**Comment by afragen** [comment]
I think a hook might be better. Well, 2 hooks, one to add and one to remove. 

I have some thoughts on how to accomplish this.

**Comment by afragen** [comment]
I'm working through this feature.

I looks like a filter returning an array will work well. So far the filter needs to return an array of the following format.

```php
$extra_constants = array(
    'my_new_constant' => array(
        'value' => 'abc123',
       'raw' => false,
   )
);
```

The `raw` key is a boolean as to whether the `value` is kept as a string ( `false` ) or converted to it's raw value as in a boolean. The `value` must be passed as a string.

**Comment by afragen** [comment]
@cartpauj give the `develop` branch a spin and let me know what you think.

https://github.com/afragen/wp-debugging/commit/9871037c63c4a9d48c3bdefffa43e39e757ada97

**Comment by cartpauj** [comment]
Thanks @afragen - I'll give it a try hopefully today or tomorrow and let you know how it went.

**Comment by cartpauj** [comment]
The following quick and dirty test on my development site worked a treat, thanks!

```PHP
  function integrate_wp_debugging($user_defined_constants) {
    if(!defined('MY_CUSTOM_DEBUG') || MY_CUSTOM_DEBUG === false) {
      // if raw is true, then value will be converted to boolean
      $user_defined_constants['MY_CUSTOM_DEBUG'] = array('value' => 'true', 'raw' => true);
    }
    
    return $user_defined_constants;
  }
  add_filter('wp_debugging_add_constants', 'integrate_wp_debugging');
```

**Comment by afragen** [comment]
In this case the default is `'raw' = true` so you don’t need to add that if your value is going to be a boolean. 

On another note, how was the readme? Understandable?

**Comment by cartpauj** [comment]
Yes, the readme was very understandable. The only critique I would have is the example code doesn't have a param being passed into the filter callback here: https://github.com/afragen/wp-debugging/commit/9871037c63c4a9d48c3bdefffa43e39e757ada97#diff-04c6e90faac2675aa89e2176d2eec7d8R70

**Comment by afragen** [comment]
Since the param is an empty array does it really matter?  I have tried to see what happens if there are 2 or more filters.

**Comment by cartpauj** [comment]
I didn't test it without a param, I `think` WP might bark at that where there is at least one param being passed in.

With two or more callbacks on the filter, the second one needs to be able to accept the array the first one altered and be able to append its own defines to it and pass along to the 3rd etc.

```PHP
  function integrate_wp_debugging($user_defined_constants) {
    if(!defined('MY_CUSTOM_DEBUG') || MY_CUSTOM_DEBUG === false) {
      // if raw is true, then value will be converted to boolean
      $user_defined_constants['MY_CUSTOM_DEBUG'] = array('value' => 'true', 'raw' => true);
    }
    
    return $user_defined_constants;
  }
  add_filter('wp_debugging_add_constants', 'integrate_wp_debugging', 10, 1);

  function integrate_wp_debugging_2($user_defined_constants) {
    if(!defined('MY_CUSTOM_DEBUG_2') || MY_CUSTOM_DEBUG_2 === false) {
      // if raw is true, then value will be converted to boolean
      $user_defined_constants['MY_CUSTOM_DEBUG_2'] = array('value' => 'true', 'raw' => true);
    }
    
    return $user_defined_constants;
  }
  add_filter('wp_debugging_add_constants', 'integrate_wp_debugging_2', 11, 1);
```

**Comment by afragen** [comment]
Yeah. I’ll update the readme. Thanks.

**Comment by cartpauj** [comment]
Thanks @afragen

**Comment by afragen** [comment]
It’s a great feature.
