### ISSUE TITLE
Error message persists after disabling plugin.

### ISSUE THREAD

**Issue by bahia0019** [afragen/wp-debugging#8]
Possibly a Multisite situation (haven't tested on single install).
I Network Activated the Debugger to see if there was a reason a plugin wasn't updating, and got the message "The WP Debugging plugin must have a wp-config.php file that is writable by the filesystem."

**I deactivated the plugin. But the error message persisted.** It shows on the admin of all sub-sites. It also oddly shows in one of my dashboard widgets.

<img width="1440" alt="Screen Shot 2020-02-13 at 1 03 57 PM" src="https://user-images.githubusercontent.com/1586037/74480421-bc894e80-4e65-11ea-961b-a5ec5bd13918.png">

**Comment by afragen** [comment]
Are you certain that the plugin is deactivated in network admin and on all sub-sites?

**Comment by bahia0019** [comment]
Yes, Network Activated, and Network Deactivated.

**Comment by afragen** [comment]
That notice comes from https://github.com/afragen/wp-debugging/blob/0c37def1ff20e393e61965ecfc3f607ed89b50fd/src/Bootstrap.php#L73

There's no way it happens if the plugin isn't active.

**Comment by bahia0019** [comment]
Well, it's certainly there. 
I activated it, it showed up. I deactivated it. Still there.
I cleared all my caches at Closte, and dropped it into Dev mode too.

**Comment by afragen** [comment]
I don’t know what to say. You could rename the folder in `wp-content/plugins` and I know that would deactivate the plugin for certain.

**Comment by bahia0019** [comment]
OK... So FIRST and foremost: I'm an idiot.
Somehow I was confusing the WP Debugger plugin and the Github Updater Support plugin.
The WP Debugger _was_ active. I realized what an idiot I am, and disabled that for now (all good).

However, this notice popped up when I deleted the Github Updater Support plugin.
Not sure if what caused that. But figured it might be of interest to you.
<img width="1428" alt="Screen Shot 2020-02-14 at 12 04 05 PM" src="https://user-images.githubusercontent.com/1586037/74564046-f5d3c400-4f22-11ea-8121-05f00842dbee.png">

**Comment by afragen** [comment]
I think that solves the why the notice is still present problem. GitHub Updater Support does include and activate WP Debugging as a dependency. 😬

However, you still don't have a writable `wp-config.php` file and that is a requirement for the plugin to function.

**Comment by bahia0019** [comment]
I understand that. That was not part of my "confusion." 😂
My config is locked down, so that's not changing.

Thanks for humoring me.
